function Jul0607 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  JUL0607 = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  JUL0607 = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  JUL0607 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.

%TPL = importfile("Jul23-24.xlsx")

%  Example:
%  Jul0607 = importfile("C:\Users\shayn\OneDrive\Desktop\EE461\Project\TPL\Jul06-07.xlsx", "Sheet1", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Mar-2025 12:28:40

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 20);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["MONTH", "GENERATED", "SENT_OUT", "BILLED","VarName5", "PARASITIC", "LINE", "TOTAL", "PARASITIC_PERCENTAGE", "LINE_PERCENTAGE", "TOTAL_PERCENTAGE", "AVERAGE_PARASITIC_PAST_12_MONTHS", "AVERAGE_LINE_PAST_12_MONTHS", "AVERAGE_TOTAL_PAST_12_MONTHS", "TARGET_PERCENTAGE", "FUEL_USE", "DIESEL_GEN", "RE_GEN", "FUEL_EFFICIENCY_DIESEL", "FUEL_EFFICIENCY_WITH_RE"];
opts.VariableTypes = ["datetime", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double","double",  "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["MONTH", "GENERATED", "SENT_OUT", "BILLED","VarName5", "PARASITIC", "LINE", "TOTAL", "RE_GEN"], "EmptyFieldRule", "auto");


% Import the data
Jul0607 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Jul0607 = [Jul0607; tb]; %#ok<AGROW>
end

%% Remove Redunted Columns
Jul0607 = removevars(Jul0607,["VarName5"]);
%% Remove Rows Or Coulmns
Jul0607([1],:) = [];
size(Jul0607);
Jul0607([223:240],:) = [];
size(Jul0607);
%% Fill Missing Entries
Jul0607 = fillmissing(Jul0607,'constant',0,'DataVariables',{'RE_GEN'});
Jul0607 = fillmissing(Jul0607,'next','DataVariables',{'MONTH','GENERATED', 'SENT_OUT', 'BILLED','PARASITIC', 'LINE', 'TOTAL', 'PARASITIC_PERCENTAGE', 'LINE_PERCENTAGE', 'TOTAL_PERCENTAGE','AVERAGE_PARASITIC_PAST_12_MONTHS','AVERAGE_LINE_PAST_12_MONTHS', 'AVERAGE_TOTAL_PAST_12_MONTHS', 'TARGET_PERCENTAGE', 'FUEL_USE', 'DIESEL_GEN', 'FUEL_EFFICIENCY_DIESEL', 'FUEL_EFFICIENCY_WITH_RE'});
end

